app:
  name: Golang_starter
  debug: true

server:
  address: 9090

context:
  timeout: 5

mariadb:
  host: localhost
  port: 3306
  user: root
  pass: secret1234
  name: lucy

mongo:
  host: localhost
  port: 27017
  user:
  pass:
  name: golang_starter

jwt:
  secret: JwtSecretBroh
  lifetime: 60

admin:
  username: vian
  password: 12345678